// Generated by CoffeeScript 1.3.3
(function() {
  var Foo;

  Foo = (function() {

    function Foo() {
      "foo";

    }

    Foo.prototype.bar = function() {
      return "baz";
    };

    return Foo;

  })();

}).call(this);
